/* This file is automatically generated by scripts/option-groups.awk
   in the EGLIBC source tree.

   It defines macros that indicate which EGLIBC option groups were
   configured in 'option-groups.config' when this C library was
   built.  For each option group named OPTION_foo, it #defines
   __OPTION_foo to be 1 if the group is enabled, or leaves that
   symbol undefined if the group is disabled.  */

#ifndef __GNU_OPTION_GROUPS_H
#define __GNU_OPTION_GROUPS_H

/* #undef __OPTION_EGLIBC_ADVANCED_INET6 */
#define __OPTION_EGLIBC_BACKTRACE 1
/* #undef __OPTION_EGLIBC_BSD */
/* #undef __OPTION_EGLIBC_CATGETS */
#define __OPTION_EGLIBC_CHARSETS 1
#define __OPTION_EGLIBC_CXX_TESTS 1
/* #undef __OPTION_EGLIBC_DB_ALIASES */
/* #undef __OPTION_EGLIBC_ENVZ */
/* #undef __OPTION_EGLIBC_FSTAB */
#define __OPTION_EGLIBC_GETLOGIN 1
#define __OPTION_EGLIBC_INET 1
#define __OPTION_EGLIBC_LIBM 1
/* #undef __OPTION_EGLIBC_LOCALES */
#define __OPTION_EGLIBC_LOCALE_CODE 1
/* #undef __OPTION_EGLIBC_NIS */
#define __OPTION_EGLIBC_NSSWITCH 1
#define __OPTION_EGLIBC_RCMD 1
/* #undef __OPTION_EGLIBC_SPAWN */
/* #undef __OPTION_EGLIBC_STREAMS */
#define __OPTION_EGLIBC_SUNRPC 1
#define __OPTION_EGLIBC_UTMP 1
#define __OPTION_EGLIBC_UTMPX 1
/* #undef __OPTION_EGLIBC_WORDEXP */
#define __OPTION_POSIX_C_LANG_WIDE_CHAR 1
#define __OPTION_POSIX_REGEXP 1
#define __OPTION_POSIX_WIDE_CHAR_DEVICE_IO 1

#endif /* __GNU_OPTION_GROUPS_H */
